simulation_parameters:
  enable_dust_drift: true
  enable_dust_growth: true
  enable_gas_evolution: true
  enable_two_dust_populations: false
  fragmentation_velocity: 500.0
  fragmentation_factor: 0.37
  number_of_dust_particles: 1000
  number_of_grid_points: 1000
  inner_radius_au: 1.0
  outer_radius_au: 50.0
  initial_gas_sigma0_msun_per_au2: 3.33e-06
  sigma_profile_exponent: -0.5
  alpha_viscosity: 0.0001
  star_mass_msun: 1.0
  aspect_ratio_at_1au: 0.05
  flaring_index: 0.0
  deadzone_inner_radius_au: 2.7
  deadzone_outer_radius_au: 24.0
  deadzone_inner_transition_width_mult: 0.5
  deadzone_outer_transition_width_mult: 0.5
  deadzone_alpha_reduction: 0.0001
  initial_dust_to_gas_ratio: 0.01
  population_one_mass_ratio: 0.85
  micro_particle_size_cm: 0.01
  one_size_particle_value_cm: 1.0
  dust_particle_density_g_cm3: 1.6
  disk_mass_dust: 0.01
  input_file_path: ''
  output_directory_name: run_alpha_0p0001_alphared_0p0001_sigmaexp_m0p5_dztrans_0p5_ufrag_500_flat_Ndust1000/
  fixed_time_step: 0.0
  total_simulation_time: 500000.0
  output_write_frequency: 1000
  simulation_start_time: 0.0
